print("elements in set 1")
set1=eval(input())
print()
print("elements in set 2")
print()
set2=eval(input())
print()
finalset=set1.difference(set2)
print("distinct elements from set 1 differ by set 2 are :-")
print(finalset)