print("elements in set 1")
set1=eval(input())
print()
print("elements in set 2")
print()
set2=eval(input())
print()
finalset=set1.symmetric_difference(set2)
print("elements that are present in either set but not in both are :-")
print(finalset)