print("employers in department 1")
set1=eval(input())
print()
print("employers in department 2")
print()
set2=eval(input())
print()
finalset=set1.intersection(set2)
print("employees working in both departments are :-")
print(finalset)