print("Students atended in event 1")
set1=eval(input())
print()
print("Students atended in event 2")
print()
set2=eval(input())
print()
finalset=set1.symmetric_difference(set2)
print(" Students atended in event only one event is :-")
print(finalset)